name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, opened, reopened]
  merge_group:

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: ['14', '16', '18']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Update npm
        if: matrix.node == '14'
        run: npm i -g npm@8
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - name: Lint
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == '18' }}
        run: npm run ci:lint
      - name: Vulnerabilities
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == '18' }}
        run: npm audit
      - name: Run tests
        if: ${{ matrix.os != 'ubuntu-latest' || matrix.node != '18' }}
        run: npm run ci:test:only
        env:
          CI: true
      - name: Run tests with coverage
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == '18' }}
        run: npm run ci:coverage
        env:
          CI: true
      - uses: codecov/codecov-action@v3
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == '18' }}
        with:
          commit_parent: ${{ github.event.pull_request.head.sha }}
      - name: Run all tests
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == '18' }}
        run: npm run ci:test
        env:
          CI: true
